#!/usr/bin/env python3

# Turku backups - storage module
# Copyright (C) 2015-2020 Canonical Ltd., Ryan Finnie and other contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

import sys
from turku_storage import ping
sys.exit(ping.main())
